const sneakersData = [
  {
    id: "air-jordan-1-black-bloodline-pe",
    title: "Air Jordan 1 High OG 'Black Bloodline' PE",
    titleEn: "Air Jordan 1 High OG 'Black Bloodline' PE",
    subtitle: "Friends & Family Sample (2019)",
    subtitleEn: "Friends & Family Sample (2019)",
    sku: "961539 (Serial: ES007436)",
    colorway: "Black/Gym Red-White",
    retailPrice: "N/A (PE Exclusive)",
    releaseDate: "12/2019",
    editionType: "PE Sample",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7 US",
    image: "jordan1_pe_bloodline_friendsandfamily_sample.png",
    badge: "Sample PE",
    shortDesc: "Phiên bản giới hạn Friends & Family Sample, sở hữu chi tiết thiết kế độc bản.",
    story: "<p>Nếu phiên bản thương mại Air Jordan 1 'Bloodline' trắng/đen/đỏ ra mắt vào dịp Black Friday 2019 vốn rất quen thuộc với giới mộ điệu, thì tác phẩm này lại mang một thân phận hoàn toàn khác biệt.</p><p>Đặc điểm ăn tiền tạo nên giá trị sưu tầm độc bản của dòng PE chính thức nằm ở việc chỉ có 93 đôi được sản xuất trên toàn cầu dành riêng cho nội bộ.</p><p>Tuy nhiên, tác phẩm hiện đang ngự trị trong bộ sưu tập cá nhân của Lộc An lại mang một ý nghĩa cao hơn thế: đây là một đôi Sample nguyên bản độc nhất vô nhị từ nhà máy.</p>",
    storyEn: "<p>While the commercial 'Bloodline' release from Black Friday 2019 is widely known, this piece holds an entirely different lineage.</p><p>The true rarity lies in its strict production run of only 93 pairs worldwide, allocated exclusively for friends and family.</p><p>Above all, the piece preserved in Lộc An's archive holds even greater historical significance: an ultra-rare factory sample pair.</p>",
    exhibitionNote: "Tác phẩm thuộc phiên bản Player Exclusive kết hợp dạng bản mẫu thử nghiệm từ nhà máy, với số lượng cực kỳ giới hạn trên toàn cầu."
  },
  {
    id: "jordan-1-quai54-ff",
    title: "Air Jordan 1 High 'Quai 54' F&F",
    titleEn: "Air Jordan 1 High 'Quai 54' F&F",
    subtitle: "Friends & Family Exclusive (2017)",
    subtitleEn: "Friends & Family Exclusive (2017)",
    sku: "MNJDLS 262 767119 XC",
    colorway: "Black/Italy Blue-Black-University Red",
    retailPrice: "N/A",
    releaseDate: "07/01/2017",
    editionType: "F&F",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7.5 US",
    image: "jordan_quai54_friendsandfamily_sample.png",
    badge: "F&F EXCLUSIVE",
    shortDesc: "Phiên bản Friends & Family cực hiếm dành riêng cho giải đấu bóng rổ Paris.",
    story: "<p>Được thiết kế độc quyền cho giải đấu bóng rổ đường phố danh giá Quai 54 tại Paris, phiên bản này không bao giờ được phát hành thương mại rộng rãi.</p><p>Sự kết hợp màu sắc biểu tượng đại diện cho tinh thần thể thao đỉnh cao và văn hóa sát mặt đất.</p>",
    storyEn: "<p>Designed exclusively for the prestigious Quai 54 streetball tournament in Paris, this version was never released to the general public.</p>",
    exhibitionNote: "Phiên bản đặc biệt giới hạn cho khách mời và vận động viên tại giải đấu Quai 54."
  },
  {
    id: "sbdunk-yutohorigome-matcha",
    title: "Nike SB Dunk Low 'Yuto Horigome' Matcha",
    titleEn: "Nike SB Dunk Low 'Yuto Horigome' Matcha",
    subtitle: "Signed Edition (2023)",
    subtitleEn: "Signed Edition (2023)",
    sku: "FN1288-200",
    colorway: "Sail/Asparagus-Malachite",
    retailPrice: "$130 USD",
    releaseDate: "08/29/2023",
    editionType: "Signed Edition",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7 US",
    image: "sbdunk_yutohorigome_matcha.png",
    badge: "SIGNED EDITION",
    shortDesc: "Phiên bản chữ ký trực tiếp từ huyền thoại trượt ván Olympic Yuto Horigome.",
    story: "<p>Đánh dấu cột mốc lịch sử của skateboard tại Thế vận hội, phiên bản kết hợp cùng Yuto Horigome mang phối màu lấy cảm hứng từ trà xanh Matcha tinh tế.</p><p>Đôi giày trong kho lưu trữ sở hữu chữ ký tay trực tiếp của vận động viên.</p>",
    storyEn: "<p>Marking a historic milestone for Olympic skateboarding, this collaboration with Yuto Horigome features clean matcha-inspired tones.</p>",
    exhibitionNote: "Sản phẩm có chữ ký xác thực trực tiếp từ Yuto Horigome."
  },
  {
    id: "offwhite-jordan-1-unc",
    title: "Off-White x Air Jordan 1 'UNC'",
    titleEn: "Off-White x Air Jordan 1 'UNC'",
    subtitle: "Archive Edition (2018)",
    subtitleEn: "Archive Edition (2018)",
    sku: "AQ0818-148",
    colorway: "White/Dark Powder Blue-Cone",
    retailPrice: "$190 USD",
    releaseDate: "06/19/2018",
    editionType: "Archive Edition",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7 US",
    image: "jordan1_vaa_alaska.png",
    badge: "ARCHIVE EDITION",
    shortDesc: "Phiên bản đặc biệt từ quỹ lưu trữ nghệ thuật chính thức của Virgil Abloh.",
    story: "<p>Tác phẩm kinh điển mang ngôn ngữ thiết kế deconstructed đặc trưng của Virgil Abloh, tri ân ngôi trường đại học alma mater UNC của Michael Jordan.</p>",
    storyEn: "<p>A quintessential piece embodying Virgil Abloh's signature deconstructed design language, paying homage to Michael Jordan's alma mater.</p>",
    exhibitionNote: "Tác phẩm nghệ thuật mang tính biểu tượng trong kỷ nguyên thiết kế hiện đại."
  }
];
