const sneakersData = [
  {
    id: "air-jordan-1-black-bloodline-pe",
    title: "Air Jordan 1 High OG 'Black Bloodline' PE",
    titleEn: "Air Jordan 1 High OG 'Black Bloodline' PE",
    subtitle: "Friends & Family Sample (2019)",
    subtitleEn: "Friends & Family Sample (2019)",
    sku: "961539 (Serial: ES007436)",
    colorway: "Black/Gym Red-White",
    retailPrice: "N/A (PE Exclusive)",
    retailPriceEn: "N/A (PE Exclusive)",
    releaseDate: "12/2019",
    editionType: "PE Sample",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7 US",
    image: "jordan1_pe_bloodline_friendsandfamily_sample.png",
    badge: "Sample PE",
    shortDesc: "Phiên bản giới hạn Friends & Family Sample, sở hữu chi tiết thiết kế độc bản.",
    shortDescEn: "Limited Friends & Family Sample edition featuring unique design details.",
    story: "<p>Nếu phiên bản thương mại Air Jordan 1 'Bloodline' trắng/đen/đỏ ra mắt vào dịp Black Friday 2019 vốn rất quen thuộc với giới mộ điệu, thì tác phẩm này lại mang một thân phận hoàn toàn khác biệt trong thế giới sưu tầm.</p><p>Đặc điểm ăn tiền tạo nên giá trị sưu tầm độc bản của dòng PE (Player Exclusive) chính thức nằm ở việc chỉ có đúng 93 đôi được sản xuất trên toàn cầu dành riêng cho nội bộ cấp cao và vận động viên thân thiết.</p><p>Tuy nhiên, tuyệt phẩm hiện đang ngự trị trong kho lưu trữ cá nhân của Lộc An lại mang một ý nghĩa lịch sử cao hơn thế: đây không chỉ là một phiên bản F&F thông thường, mà là một đôi <strong>Factory Sample</strong> nguyên bản độc nhất vô nhị từ nhà máy với các chi tiết thông số nội bộ được mã hóa cực kỳ hiếm thấy.</p><p>Sự kết hợp giữa chất liệu da cao cấp, đường viền đỏ sắc nét cùng dải serial number dập chìm bên trong cổ giày đã biến đôi giày này trở thành một báu vật thực sự, nơi ranh giới giữa giày thể thao và tác phẩm nghệ thuật đương đại bị xóa nhòa hoàn toàn.</p>",
    storyEn: "<p>While the commercial Air Jordan 1 'Bloodline' release from Black Friday 2019 is widely recognized by sneaker enthusiasts, this specific piece holds an entirely different, highly exclusive lineage.</p><p>The true rarity lies in its strict production run of only 93 pairs worldwide, allocated exclusively for top-tier brand insiders and close family members.</p><p>Above all, the piece preserved in Lộc An's personal archive holds even greater historical significance: it is an ultra-rare factory sample pair featuring internal coded specifications.</p><p>The combination of premium leather, striking red piping, and internal serial numbering transforms this artifact into a true museum-grade piece.</p>",
    exhibitionNote: "Tác phẩm thuộc phiên bản Player Exclusive kết hợp dạng bản mẫu thử nghiệm từ nhà máy (Factory Sample), với số lượng cực kỳ giới hạn trên toàn cầu dành riêng cho nội bộ thương hiệu. Do không phát hành thương mại, sản phẩm hoàn toàn không có giá niêm yết gốc (Retail Price: N/A) và mang giá trị lưu trữ độc bản.",
    exhibitionNoteEn: "This piece belongs to an ultra-rare hybrid Player Exclusive and factory sample edition, strictly limited worldwide for brand insiders. Not released commercially, it carries no official retail price (Retail Price: N/A) and holds irreplaceable archive value."
  },
  {
    id: "jordan-1-quai54-ff",
    title: "Air Jordan 1 High 'Quai 54' F&F",
    titleEn: "Air Jordan 1 High 'Quai 54' F&F",
    subtitle: "Friends & Family Exclusive (2017)",
    subtitleEn: "Friends & Family Exclusive (2017)",
    sku: "MNJDLS 262 767119 XC",
    colorway: "Black/Italy Blue-Black-University Red",
    retailPrice: "N/A",
    retailPriceEn: "N/A",
    releaseDate: "07/01/2017",
    editionType: "F&F",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7.5 US",
    image: "jordan_quai54_friendsandfamily_sample.png",
    badge: "F&F EXCLUSIVE",
    shortDesc: "Phiên bản Friends & Family cực hiếm dành riêng cho giải đấu bóng rổ Paris.",
    shortDescEn: "Ultra-rare Friends & Family edition dedicated to the Paris streetball tournament.",
    story: "<p>Được thiết kế độc quyền cho giải đấu bóng rổ đường phố danh giá nhất hành tinh – Quai 54 tại Paris, phiên bản Air Jordan 1 này đứng ngoài mọi guồng quay phát hành thương mại thông thường của Nike.</p><p>Sự pha trộn màu sắc đầy nghệ thuật giữa sắc đen tuyền chủ đạo, điểm xuyết các mảng màu Italy Blue sâu thẳm và University Red rực rỡ đã tái hiện hoàn hảo năng lượng bùng nổ của những mặt sân bê tông thủ đô nước Pháp.</p><p>Những đôi giày mang mã định danh F&F (Friends & Family) này chưa bao giờ xuất hiện trên kệ hàng bán lẻ. Chúng được trao tận tay cho các huyền thoại bóng rổ khách mời và ban tổ chức giải đấu, biến mỗi đôi giày thành một nhân chứng sống cho văn hóa sát mặt đất đỉnh cao.</p><p>Việc sở hữu một siêu phẩm F&F trong bộ sưu tập không chỉ là minh chứng cho tầm nhìn sưu tầm sắc bén mà còn là sự trân trọng đối với di sản văn hóa bóng rổ đường phố toàn cầu.</p>",
    storyEn: "<p>Designed exclusively for the world's most prestigious streetball tournament – Quai 54 in Paris, this Air Jordan 1 edition stands completely outside standard commercial retail channels.</p><p>The artistic color palette blending deep black with Italy Blue and vibrant University Red perfectly captures the explosive energy of Parisian concrete courts.</p><p>These Friends & Family (F&F) designated pairs never hit retail shelves; instead, they were gifted strictly to invited basketball legends and tournament organizers.</p><p>Owning such an F&F masterpiece represents a deep appreciation for global streetball culture and elite archival collecting.</p>",
    exhibitionNote: "Tác phẩm thuộc phiên bản đặc biệt (F&F). Các phiên bản dạng này (như Promo Sample, Player Exclusive hoặc Friends & Family) chỉ được sản xuất giới hạn để dành riêng cho vận động viên, người thân hoặc nội bộ thương hiệu. Do không được phát hành thương mại tại các cửa hàng bán lẻ, tác phẩm không có giá niêm yết gốc (Retail Price: N/A) và sở hữu giá trị sưu tầm đặc biệt trên thị trường quốc tế.",
    exhibitionNoteEn: "This piece belongs to a special Friends & Family (F&F) edition. Such pairs (like Promo Samples, Player Exclusives, or F&F) were strictly produced in limited numbers for athletes, relatives, or brand personnel. Not released commercially at retail, it carries no official retail price (Retail Price: N/A) and holds exceptional collectible value globally."
  },
  {
    id: "sbdunk-yutohorigome-matcha",
    title: "Nike SB Dunk Low 'Yuto Horigome' Matcha",
    titleEn: "Nike SB Dunk Low 'Yuto Horigome' Matcha",
    subtitle: "Signed Edition (2023)",
    subtitleEn: "Signed Edition (2023)",
    sku: "FN1288-200",
    colorway: "Sail/Asparagus-Malachite",
    retailPrice: "$130 USD",
    retailPriceEn: "$130 USD",
    releaseDate: "08/29/2023",
    editionType: "Signed Edition",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7 US",
    image: "sbdunk_yutohorigome_matcha.png",
    badge: "SIGNED EDITION",
    shortDesc: "Phiên bản chữ ký trực tiếp từ huyền thoại trượt ván Olympic Yuto Horigome.",
    shortDescEn: "Directly signed edition from Olympic skateboarding legend Yuto Horigome.",
    story: "<p>Đánh dấu cột mốc lịch sử khi bộ môn skateboard chính thức bước lên sân chơi Thế vận hội Olympic, màn kết hợp giữa Nike SB và thần đồng trượt ván Yuto Horigome đã tạo ra một trong những phối màu được thèm muốn nhất thập kỷ.</p><p>Lấy cảm hứng từ văn hóa trà xanh Matcha thanh bình kết hợp cùng chất liệu da lộn thượng hạng, từng chi tiết trên giày đều kể câu chuyện về sự kỷ luật và nghệ thuật đường phố Nhật Bản.</p><p>Điểm nhấn vô giá của tác phẩm lưu trữ này nằm ở chữ ký tay trực tiếp được chính Yuto Horigome thực hiện, nâng tầm đôi giày từ một thiết bị trượt ván thông thường thành một tác phẩm nghệ thuật có một không hai.</p>",
    storyEn: "<p>Marking a historic milestone as skateboarding officially entered the Olympic stage, the collaboration between Nike SB and prodigy Yuto Horigome created one of the most coveted colorways of the decade.</p><p>Inspired by serene matcha green culture combined with premium suede, every detail tells a story of Japanese discipline and street art.</p><p>The priceless highlight of this archival piece is the direct autograph signed by Yuto Horigome himself.</p>",
    exhibitionNote: "Sản phẩm có chữ ký xác thực trực tiếp từ Yuto Horigome.",
    exhibitionNoteEn: "This product features verified direct autograph from Yuto Horigome."
  },
  {
    id: "offwhite-jordan-1-unc",
    title: "Off-White x Air Jordan 1 'UNC'",
    titleEn: "Off-White x Air Jordan 1 'UNC'",
    subtitle: "Archive Edition (2018)",
    subtitleEn: "Archive Edition (2018)",
    sku: "AQ0818-148",
    colorway: "White/Dark Powder Blue-Cone",
    retailPrice: "$190 USD",
    retailPriceEn: "$190 USD",
    releaseDate: "06/19/2018",
    editionType: "Archive Edition",
    condition: "Deadstock (Brand New)",
    conditionEn: "Deadstock (Brand New)",
    size: "7 US",
    image: "jordan1_vaa_alaska.png",
    badge: "ARCHIVE EDITION",
    shortDesc: "Phiên bản đặc biệt từ quỹ lưu trữ nghệ thuật chính thức của Virgil Abloh.",
    shortDescEn: "Special piece from Virgil Abloh's official artistic archive fund.",
    story: "<p>Là một trong những chương cuối cùng đầy cảm xúc trong bộ sưu tập 'The Ten' huyền thoại, Off-White x Air Jordan 1 'UNC' dưới bàn tay thiên tài của Virgil Abloh đã định nghĩa lại hoàn toàn cách con người nhìn nhận về thiết kế giày thể thao.</p><p>Lấy cảm hứng từ ngôi trường đại học alma mater UNC nơi Michael Jordan từng theo học, Abloh đã giữ nguyên các đường cắt may thô, nhãn mác lộ thiên và dòng chữ Helvetica trứ danh.</p><p>Tác phẩm này không chỉ đại diện cho đỉnh cao của văn hóa sneaker thế kỷ 21 mà còn là lời tri ân vĩnh cửu đối với di sản sáng tạo mà Virgil Abloh đã để lại cho thế giới thời trang đường phố.</p>",
    storyEn: "<p>As one of the most emotional final chapters in the legendary 'The Ten' collection, the Off-White x Air Jordan 1 'UNC' under Virgil Abloh's genius redefined sneaker design.</p><p>Inspired by Michael Jordan's alma mater, Abloh retained raw stitching, exposed foam, and signature Helvetica text.</p><p>This masterpiece represents both the peak of 21st-century sneaker culture and a permanent tribute to Virgil Abloh's legacy.</p>",
    exhibitionNote: "Tác phẩm nghệ thuật mang tính biểu tượng trong kỷ nguyên thiết kế hiện đại.",
    exhibitionNoteEn: "An iconic art piece of the modern design era."
  }
];
